version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 1.32.1
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@hapi/hapi"
    versions:
    - 20.0.0
    - 20.1.1
  - dependency-name: eslint-config-salesflare
    versions:
    - 4.5.0
    - 4.6.0
  - dependency-name: "@hapi/lab"
    versions:
    - 24.1.0
    - 24.1.1
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: "@hapi/accept"
    versions:
    - 5.0.2
  - dependency-name: "@hapi/hoek"
    versions:
    - 9.1.1
  - dependency-name: rollup-plugin-terser
    versions:
    - 5.3.1
  - dependency-name: rollup-plugin-babel
    versions:
    - 4.4.0
  - dependency-name: rimraf
    versions:
    - 3.0.2
